version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: p2p-backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=production

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: p2p-frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - NEXT_PUBLIC_BACKEND_URL=https://filesharing.ramakrishna.tech/api
      - NODE_ENV=production
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: p2p-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    networks:
      - app-network
    depends_on:
      - backend
      - frontend

  certbot:
    image: certbot/certbot
    container_name: p2p-certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email rahul.fm23@gmail.com --agree-tos --no-eff-email --non-interactive -d filesharing.ramakrishna.tech

volumes:
  certbot-etc:
  certbot-var:
  web-root:

networks:
  app-network:
    driver: bridge